name: Test Terraform CI

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to test"
        required: true
        default: dev
      tf_dir:
        description: "Terraform directory"
        required: true
        default: test/terraform

jobs:
  call-terraform-ci:
    uses: ./.github/workflows/terraform-ci.yml
    with:
      env: ${{ inputs.env }}
      tf_dir: ${{ inputs.tf_dir }}
    secrets:
      AWS_MANAGEMENT_ROLE_ARN: dummy
      AWS_TARGET_ROLE_ARN: dummy
