name: Terraform CI Testing

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      tf_dir:
        required: true
        type: string
    secrets:
      AWS_MANAGEMENT_ROLE_ARN:
        required: false
      AWS_TARGET_ROLE_ARN:
        required: false
      CHECKOV_API_KEY: # Verify Naming (if exists)
        required: false
      GITLEAKS_LICENSE:
        required: false

env:
  TF_INPUT: false
  TF_IN_AUTOMATION: true
  TF_DIR: ${{ inputs.tf_dir }}
  TF_VER: 1.8.5
  AWS_REGION: us-east-1
  REPORT_RETENTION_DAYS: 1

jobs:
  set-timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.set_timestamp.outputs.timestamp }}
    steps:
      - name: Set Timestamp
        id: set_timestamp
        run: echo "timestamp=$(date -u +%Y%m%dT%H%M%SZ)" >> $GITHUB_OUTPUT

  # aws-credentials-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Configure AWS Master(Mgmt) Credentials
  #       uses: aws-actions/configure_aws_credentials@v5
  #       with:
  #         aws-region: ${{ env.AWS_REGION }}
  #         role-to-assume: ${{ secrets.AWS_MANAGEMENT_ROLE_ARN }}
  #         role-session-name: MgmtOIDC
      
  #     - name: Configure AWS Target(ENV) Credentials
  #       uses: aws-actions/configure_aws_credentials@v5
  #       with:
  #         aws-region: ${{ env.AWS_REGION }}
  #         role-to-assume: ${{ secrets.AWS_TARGET_ROLE_ARN }}
  #         role-session-name: TargetOIDC
  #         role-chaining: true
      
  #     - name: Verify Target Caller Identity
  #       run: |
  #         set -euo pipefail
  #         aws sts get-caller-identity
  
  terraform-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VER }}
        
      - name: Terraform Init
        working-directory: "${{ github.workspace }}/${{ env.TF_DIR }}"
        run: terraform init -backend=false -input=false
      
      - name: Terraform Format
        working-directory: "${{ github.workspace }}/${{ env.TF_DIR }}"
        run: |
          set -euo pipefail
          terraform fmt -check -recursive

  terraform-validate:
    runs-on: ubuntu-latest
    needs: terraform-format
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VER }}
        
      - name: Terraform Init
        working-directory: "${{ github.workspace }}/${{ env.TF_DIR }}"
        run: terraform init -backend=false -input=false
      
      - name: Terraform Validate
        working-directory: "${{ github.workspace }}/${{ env.TF_DIR }}"
        run: |
          set -euo pipefail
          terraform validate

  trivy-scan:
    runs-on: ubuntu-latest
    needs: [set-timestamp, terraform-validate]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Create Report Directory
        run: mkdir -p "${GITHUB_WORKSPACE}/${TF_DIR}/trivy-reports"

      - name: Run Trivy Scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-ref: "${{ github.workspace }}/${{ env.TF_DIR }}"
          scan-type: config
          scanners: misconfig,secret,license
          tf-vars: "${{ github.workspace }}/${{ env.TF_DIR }}/env/${{ inputs.env }}.tfvars"
          hide-progress: false
          format: json
          output: "${{ github.workspace }}/${{ env.TF_DIR }}/trivy-reports/trivy-report-json.json"
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN' # limiting severity for fail excludes from report
          exit-code: 0
      
      - name: Ensure Trivy Report was Generated
        run: | # Due to requirement for conditionally failing, previous job will not fail pipeline from errors
          if [[ ! -f "${GITHUB_WORKSPACE}/${TF_DIR}/trivy-reports/trivy-report-json.json" ]]; then
            echo "::error:: trivy scan report was not generated and cannot be processed. Blocking deployment to all environments."
            exit 1
          fi

      - name: Count Trivy Findings by Severity
        id: trivy-count
        env:
          TRIVY_REPORT: "${{ github.workspace }}/${{ env.TF_DIR }}/trivy-reports/trivy-report-json.json"
        run: |
          LOW=$(jq '[.Results[]? | (.Misconfigurations[]? // empty), (.Secrets[]? // empty) | select(.Severity=="LOW")] | length' "$TRIVY_REPORT")
          MEDIUM=$(jq '[.Results[]? | (.Misconfigurations[]? // empty), (.Secrets[]? // empty) | select(.Severity=="MEDIUM")] | length' "$TRIVY_REPORT")
          HIGH=$(jq '[.Results[]? | (.Misconfigurations[]? // empty), (.Secrets[]? // empty) | select(.Severity=="HIGH")] | length' "$TRIVY_REPORT")
          CRITICAL=$(jq '[.Results[]? | (.Misconfigurations[]? // empty), (.Secrets[]? // empty) | select(.Severity=="CRITICAL")] | length' "$TRIVY_REPORT")
          UNKNOWN=$(jq '[.Results[]? | (.Misconfigurations[]? // empty), (.Secrets[]? // empty) | select(.Severity=="UNKNOWN")] | length' "$TRIVY_REPORT")
          TOTAL=$((LOW + MEDIUM + HIGH + CRITICAL + UNKNOWN))

          echo "low=$LOW" >> $GITHUB_OUTPUT
          echo "medium=$MEDIUM" >> $GITHUB_OUTPUT
          echo "high=$HIGH" >> $GITHUB_OUTPUT
          echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
          echo "unknown=$UNKNOWN" >> $GITHUB_OUTPUT
          echo "total=$TOTAL" >> $GITHUB_OUTPUT

          echo "DEBUG"
          echo "$LOW low(s)"
          echo "$MEDIUM medium(s)"
          echo "$HIGH high(s)"
          echo "$CRITICAL critical(s)"
          echo "$UNKNOWN unknown(s)"
          echo "$TOTAL total"
      
      - name: Conditionally Warn Pipeline in Development or Test Environments
        # Intentionally declaring dev and test so any future environments fail by default
        if: ${{ (inputs.env == 'dev' || inputs.env == 'tst') && (steps.trivy-count.outputs.high > 0 || steps.trivy-count.outputs.critical > 0) }}
        run: |
          echo "::warning:: HIGH and/or CRITICAL vulnerabilities detected by Trivy! Deployment permitted to dev/test environment."

      - name: Conditionally Fail Pipeline in Production Environment
        # High and/or Critical vulnerabilities will block deployment to production
        if: ${{ (inputs.env == 'prod') && (steps.trivy-count.outputs.high > 0 || steps.trivy-count.outputs.critical > 0) }}
        run: |
          echo "::error:: HIGH and/or CRITICAL vulnerabilities detected by Trivy! Blocking production deployment."
          exit 1
      
      - name: Conditionally Fail Pipeline in any Other Environments
        # Creates a fail by default condition if any vulnerabilities are detected for environments not explicitly listed
        if: ${{ (inputs.env != 'dev' && inputs.env != 'tst' && inputs.env != 'prod') && (steps.trivy-count.outputs.total > 0) }}
        run: |
          echo "::error:: HIGH and/or CRITICAL vulnerabilities detected by Trivy! Blocking deployment to unknown environment."
          exit 1
      
      - name: Create Trivy Table Report
        run: |
          trivy convert --format table --exit-code 0 \
            --output ${GITHUB_WORKSPACE}/${TF_DIR}/trivy-reports/trivy-report-table.txt \
            ${GITHUB_WORKSPACE}/${TF_DIR}/trivy-reports/trivy-report-json.json

      - name: Create Trivy CSV Report
        run: |
          # if [ -f "${GITHUB_WORKSPACE}/${TF_DIR}/trivy-reports/trivy-report-json.json" ]; then
          #   jq -r '["Target","Type","ID","Resource","Severity","Title","Description"],
          #     (.Results[]? as $results|
          #       (.Misconfigurations[]? | [$results.Target, .Type, .ID, .CauseMetadata.Resource, .Severity, .Title, .Description]),
          #       (.Secrets[]? | [$results.Target, .Type, .ID, .Resource, .Severity, .Title, .Description]),
          #       (.Licenses[]? | [$results.Target, .Type, .ID, .Resource, .Severity, .Title, .Description])
          #     ) | @csv' "${GITHUB_WORKSPACE}/${TF_DIR}/trivy-reports/trivy-report-json.json" > \
          #       "${GITHUB_WORKSPACE}/${TF_DIR}/trivy-reports/trivy-report-csv.csv"
          # fi
          
          if [ -f "${GITHUB_WORKSPACE}/${TF_DIR}/trivy-reports/trivy-report-json.json" ]; then
            jq -r '["Target","Type","ID","Resource","Severity","Title","Description"],
            (.Results[]? as $results | $results.Target as $target | (
                  ($results.Misconfigurations[]? | [$target, .Type, .ID, .CauseMetadata.Resource, .Severity, .Title, .Description]),
                  ($results.Secrets[]? | [$target, "Secret", .RuleID, .Target, .Severity, .Title, .Match]),
                  ($results.Licenses[]? | [$target, "License", .Name, .PkgName, .Severity, .Name, .Category])
                )
            ) | @csv' "${GITHUB_WORKSPACE}/${TF_DIR}/trivy-reports/trivy-report-json.json" > \
              "${GITHUB_WORKSPACE}/${TF_DIR}/trivy-reports/trivy-report-csv.csv"
          fi

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        if: always() # Upload artifact(s) even if some steps fail
        with:
          name: "${{ needs.set-timestamp.outputs.timestamp }}-${{ inputs.env }}-trivy-reports"
          path: "${{ github.workspace }}/${{ env.TF_DIR }}/trivy-reports/*"
          retention-days: ${{ env.REPORT_RETENTION_DAYS }}

  checkov-scan:
    runs-on: ubuntu-latest
    needs: [set-timestamp, terraform-validate]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Create Report Directory
        run: mkdir -p "${{ github.workspace }}/${{ env.TF_DIR }}/checkov-reports/csv"
      
      - name: Pull Checkov GitHub Action and Run for JSON
        uses: bridgecrewio/checkov-action@v12
        if: always() # Ensure Checkov runs even if trivy fails
        continue-on-error: true
        with:
          api-key: "${{ secrets.CHECKOV_API_KEY || '' }}"
          directory: "${{ github.workspace }}/${{ env.TF_DIR }}"
          output_format: json
          output_file_path: "${{ github.workspace }}/${{ env.TF_DIR }}/checkov-reports"
      
      - name: Pull Checkov GitHub Action Docker Container and Run for CSV
      # Cannot output JSON and CSV at same time due to Checkov limitation with ',' for output_file_path for files vs directories
        uses: bridgecrewio/checkov-action@v12
        if: always() # Ensure Checkov runs even if trivy fails
        continue-on-error: true
        with:
          api-key: "${{ secrets.CHECKOV_API_KEY || '' }}"
          directory: "${{ github.workspace }}/${{ env.TF_DIR }}"
          output_format: csv # creates multiple CSV files
          output_file_path: "${{ github.workspace }}/${{ env.TF_DIR }}/checkov-reports/csv"
      
      - name: (checkov) Ensure Vulnerability Report was Generated
        run: | # Due requirement for conditionally failing, previous job will not fail pipeline from errors
          if [[ ! -f "${GITHUB_WORKSPACE}/${TF_DIR}/checkov-reports/results_json.json" ]]; then
            echo "::error:: Checkov scan report was not generated and cannot be processed. Blocking deployment to all environments."
            exit 1
          fi

      - name: (Checkov) Count Findings by Severity
        id: checkov-count
        env:
          CHECKOV_REPORT: "${{ github.workspace }}/${{ env.TF_DIR }}/checkov-reports/results_json.json"
        run: | # Creates and exports variables that count numbers of vulnerabilities for conditional security gates                   
          # #!/usr/bin/env bash
          # set -euo pipefail

          # if jq -e '.[]? | .results.failed_checks[]? | select(.severity != null and .severity != "")' "$CHECKOV_REPORT" >/dev/null; then

          #   INFO=$(jq '[.[] | .results.failed_checks[]? | select(.severity=="INFO")]   | length' "${CHECKOV_REPORT}")
          #   LOW=$(jq  '[.[] | .results.failed_checks[]? | select(.severity=="LOW")]    | length' "${CHECKOV_REPORT}")
          #   MEDIUM=$(jq '[.[] | .results.failed_checks[]? | select(.severity=="MEDIUM")] | length' "${CHECKOV_REPORT}")
          #   HIGH=$(jq '[.[] | .results.failed_checks[]? | select(.severity=="HIGH")]   | length' "${CHECKOV_REPORT}")
          #   TOTAL=$((LOW + MEDIUM + HIGH))

          #   {
          #     echo "info=$INFO"
          #     echo "low=$LOW"
          #     echo "medium=$MEDIUM"
          #     echo "high=$HIGH"
          #     echo "total=$TOTAL"
          #     echo "pass="
          #     echo "fail="
          #   } >> "$GITHUB_OUTPUT"

          # else
          #   echo "::notice:: Checkov severity scoring not populated. Falling back to pass/fail."
          #   echo "::notice:: A Checkov API key was likely not provided."

          #   PASSED=$(jq '[.[] | .summary.passed] | add' "${CHECKOV_REPORT}")
          #   FAILED=$(jq '[.[] | .summary.failed] | add' "${CHECKOV_REPORT}")

          #   {
          #     echo "info="
          #     echo "low="
          #     echo "medium="
          #     echo "high="
          #     echo "total="
          #     echo "pass=$PASSED"
          #     echo "fail=$FAILED"
          #   } >> "$GITHUB_OUTPUT"
          # fi

          #!/usr/bin/env bash
          set -euo pipefail

          if [ ! -f "$CHECKOV_REPORT" ]; then
            echo "::error:: Checkov report not found!"
            exit 1
          fi

          if jq -e '.[]? | .results.failed_checks[]? | select(.severity != null and .severity != "")' "$CHECKOV_REPORT" >/dev/null; then
            INFO=$(jq '[.results.failed_checks[]? | select(.severity=="INFO")] | length // 0' "$CHECKOV_REPORT")
            LOW=$(jq '[.results.failed_checks[]? | select(.severity=="LOW")] | length // 0' "$CHECKOV_REPORT")
            MEDIUM=$(jq '[.results.failed_checks[]? | select(.severity=="MEDIUM")] | length // 0' "$CHECKOV_REPORT")
            HIGH=$(jq '[.results.failed_checks[]? | select(.severity=="HIGH")] | length // 0' "$CHECKOV_REPORT")
            TOTAL=$((LOW + MEDIUM + HIGH))

            {
              echo "info=$INFO"
              echo "low=$LOW"
              echo "medium=$MEDIUM"
              echo "high=$HIGH"
              echo "total=$TOTAL"
              echo "pass="
              echo "fail="
            } >> "$GITHUB_OUTPUT"

          else
            echo "::notice:: Checkov severity scoring not populated. Falling back to pass/fail."
            echo "::notice:: A Checkov API key was likely not provided."
            
            PASSED=$(jq '.summary.passed // 0' "$CHECKOV_REPORT")
            FAILED=$(jq '.summary.failed // 0' "$CHECKOV_REPORT")

            {
              echo "info="
              echo "low="
              echo "medium="
              echo "high="
              echo "total="
              echo "pass=$PASSED"
              echo "fail=$FAILED"
            } >> "$GITHUB_OUTPUT"
          fi

      - name: (Checkov) Conditionally Warn Pipeline in Development or Test Environments
        # Intentionally declaring dev and test so any future environments fail by default
        if: ${{ (inputs.env == 'dev' || inputs.env == 'tst') && (steps.checkov-count.outputs.high > 0 || steps.checkov-count.outputs.fail > 0) }}
        run: |
          echo "::warning:: HIGH vulnerabilities or FAILED checks detected by Checkov! Deployment permitted to dev/test environment."

      - name: (Checkov) Conditionally Fail Pipeline in Production Environment
        # High vulnerabilities (or failed checks) will block deployment to production
        if: ${{ (inputs.env == 'prod') && (steps.checkov-count.outputs.high > 0 || steps.checkov-count.outputs.fail > 0) }}
        run: |
          echo "::error:: HIGH vulnerabilities or FAILED checks detected by Checkov! Blocking production deployment."
          exit 1
      
      - name: (Checkov) Conditionally Fail Pipeline in any Other Environments
        # Creates a fail by default condition if any vulnerabilities are detected for environments not explicitly listed
        if: ${{ (inputs.env != 'dev' && inputs.env != 'tst' && inputs.env != 'prod') && (steps.checkov-count.outputs.total > 0 || steps.checkov-count.outputs.fail > 0) }}
        run: |
          echo "::error:: Vulnerabilities or FAILED checks detected by Checkov! Blocking deployment to unknown environment."
          exit 1
      
      - name: Upload Checkov Report
        uses: actions/upload-artifact@v4
        if: always() # Upload artifact(s) even if some steps fail
        with:
          name: "${{ needs.set-timestamp.outputs.timestamp }}-${{ inputs.env }}-checkov-reports"
          path: "${{ github.workspace }}/${{ env.TF_DIR }}/checkov-reports/*"
          retention-days: ${{ env.REPORT_RETENTION_DAYS }}
          
  # terraform-init-backend:
  #   runs-on: ubuntu-latest
  #   needs: [aws-credentials-check, trivy-scan, checkov-scan]
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
      
  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v3
  #       with:
  #         terraform_version: ${{ env.TF_VER }}
      
  #     - name: Configure AWS Master(Mgmt) Credentials
  #       uses: aws-actions/configure_aws_credentials@v5
  #       with:
  #         aws-region: us-east-1
  #         role-to-assume: ${{ secrets.AWS_MANAGEMENT_ROLE_ARN }}
  #         role-session-name: MgmtOIDC
      
  #     - name: Configure AWS Target(ENV) Credentials
  #       uses: aws-actions/configure_aws_credentials@v5
  #       with:
  #         aws-region: us-east-1
  #         role-to-assume: ${{ secrets.AWS_TARGET_ROLE_ARN }}
  #         role-session-name: TargetOIDC
  #         role-chaining: true
      
  #     - name: Terraform Init (Deploy)
  #       run: |
  #         set -euo pipefail
  #         terraform -chdir="${GITHUB_WORKSPACE}/${TF_DIR}" init -input=false -reconfigure \
  #           -backend-config="env/${{ inputs.env }}/${{ inputs.env }}.tfbackend"